import React from 'react';
import { Download, FileText, BarChart3, TrendingUp, Users, Package, Calendar } from 'lucide-react';

const AdminReports = () => {
  const reportTypes = [
    { title: 'Financial Summary', desc: 'Comprehensive overview of platform revenue, commissions, and taxes.', icon: BarChart3, color: 'text-blue-600', bg: 'bg-blue-100' },
    { title: 'Sales Performance', desc: 'Detailed breakdown of sales by region, category, and time period.', icon: TrendingUp, color: 'text-green-600', bg: 'bg-green-100' },
    { title: 'User Demographics', desc: 'Analytics on customer acquisition, retention, and geographic distribution.', icon: Users, color: 'text-purple-600', bg: 'bg-purple-100' },
    { title: 'Inventory Health', desc: 'Metrics on stock levels, low-stock warnings, and top-selling products.', icon: Package, color: 'text-amber-600', bg: 'bg-amber-100' },
  ];

  const recentReports = [
    { name: 'April 2024 Financial Audit', type: 'Financial', date: '01 May 2024, 09:00 AM', generatedBy: 'System Auto' },
    { name: 'Q1 Sales Performance Report', type: 'Sales', date: '15 Apr 2024, 11:30 AM', generatedBy: 'Rohan (Admin)' },
    { name: 'Customer Retention Q1', type: 'User Demo', date: '10 Apr 2024, 02:15 PM', generatedBy: 'Sneha (Marketing)' },
  ];

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto pb-10">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-gray-900 leading-tight">Reports & Analytics</h1>
          <p className="text-sm font-medium text-gray-500">Generate, schedule, and download platform reports</p>
        </div>
      </div>

      {/* Report Generation Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {reportTypes.map((report, i) => {
          const Icon = report.icon;
          return (
            <div key={i} className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm flex flex-col sm:flex-row gap-4 sm:items-center justify-between group hover:border-green-200 transition-colors">
              <div className="flex items-start sm:items-center gap-4">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${report.bg} ${report.color}`}>
                  <Icon className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-gray-900 group-hover:text-green-700 transition-colors">{report.title}</h3>
                  <p className="text-xs font-medium text-gray-500 mt-0.5 pr-4">{report.desc}</p>
                </div>
              </div>
              <div className="shrink-0 flex gap-2">
                <button className="px-3 py-2 bg-gray-50 hover:bg-gray-100 text-gray-700 rounded-lg text-[10px] font-bold border border-gray-200 transition-colors uppercase tracking-wider">
                  Config
                </button>
                <button className="flex items-center gap-1.5 px-3 py-2 bg-[#11311F] hover:bg-[#064e3b] text-amber-500 rounded-lg text-[10px] font-bold transition-colors uppercase tracking-wider">
                  <Download className="w-3.5 h-3.5" />
                  <span>Generate</span>
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Recent Reports Table */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden mt-8">
        <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
          <h3 className="text-sm font-bold text-gray-900 flex items-center gap-2">
            <FileText className="w-4 h-4 text-gray-500" />
            Recently Generated Reports
          </h3>
          <button className="text-xs font-bold text-green-600 hover:underline">View Full History</button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="border-b border-gray-100">
              <tr className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                <th className="px-6 py-3">Report Name</th>
                <th className="px-6 py-3">Type</th>
                <th className="px-6 py-3">Generated On</th>
                <th className="px-6 py-3">Generated By</th>
                <th className="px-6 py-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {recentReports.map((rep, i) => (
                <tr key={i} className="hover:bg-gray-50/50 transition-colors">
                  <td className="px-6 py-4 text-sm font-bold text-gray-800">{rep.name}</td>
                  <td className="px-6 py-4">
                    <span className="inline-block px-2 py-1 bg-gray-100 text-gray-600 rounded text-[10px] font-bold uppercase">{rep.type}</span>
                  </td>
                  <td className="px-6 py-4 text-xs font-medium text-gray-500 flex items-center gap-1.5">
                    <Calendar className="w-3.5 h-3.5 text-gray-400" />
                    {rep.date}
                  </td>
                  <td className="px-6 py-4 text-xs font-semibold text-gray-700">{rep.generatedBy}</td>
                  <td className="px-6 py-4 text-right">
                    <button className="text-green-600 hover:text-green-800 font-bold text-xs flex items-center justify-end gap-1 w-full">
                      <Download className="w-3.5 h-3.5" /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};

export default AdminReports;
